Portfolio: mobile skeleton
VuDej/Portofolio-Projects pull request #2
Opened 2021-11-25 19:32 UTC by VuDej

Hi, I made sections about the project and the About section. I used CSS grid and flex. I copied the page from the last project, just to be all together, so Portfolio can be useful. Therefore I got 2 main tags inside the project, so if needs I will change them. Added README.md and LICENCE file. Thank you forward.

2021-11-25 23:34 UTC, Gambit142 requested changes
Hi @VuDej 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Kindly request a separate pull request for the mobile skeleton set-up which is Milestone 1. You ought to have a separate pull request for each milestone. For better understanding, kindly read this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md)

## Required Changes ♻️
_Kindly check the comments under the review for all required changes for this particular milestone._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 23:34 UTC, Gambit142 commented on index.html
> +        </div>
Kindly refer to pull request number 2 for the button interactions for this particular button.

2021-11-25 23:34 UTC, Gambit142 commented on index.html
> +        <button class='orange-button white'>See Project</button>
- [ ] Kindly refer to the pull request number for listing these badges using `ul`, `li` ,and `a` tags.
- [ ] It would be nice to follow the design for buttons and badges in this section.
Currently, your project looks like this;
![image](https://user-images.githubusercontent.com/77106962/143506563-31fa7726-8a11-4014-a931-c99134db02ee.png)
while that of Figmas look like this;
![image](https://user-images.githubusercontent.com/77106962/143506603-11a6f00e-710e-4818-a253-da0abbdf7991.png)

Kindly use the colors, fonts, margins and padding used in this template.

2021-11-25 23:34 UTC, Gambit142 commented on style.css
> +}
- [ ] Nice job using the `font-family` that was used in the template here. I would like to advise that you use a `font-size` of `40px` for this class declaration. This way, you would be following the design template perfectly

2021-11-25 23:34 UTC, Gambit142 commented on style.css
> +}
It would be nice if you adhere to the project instruction for this section. The requirements say that you should make the general container a `section` and not a `div` for semantic purposes and use `display: grid` for the parent section. Kindly implement this.

2021-11-25 23:34 UTC, Gambit142 commented on style.css
> +}
Nice job was done in the project section. Kindly use a `display: flex` to align the items for each project card as specified in the project requirement for this milestone.

2021-11-25 23:34 UTC, Gambit142 commented on style.css
> +}
- [ ] I would like to suggest that you use `display: flex` instead of grid for this section as specified in the requirements for this project.

2021-11-26 20:19 UTC, rotimiazeez approved these changes
# Hi @VuDej 👋, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 20:34 UTC, merged